---

sudo: false

language: python
cache: pip

branches:
  only:
    - master

before_script:
  - pip install tox

script: tox

notifications:
  email: false

matrix:
  fast_finish: true
  include:

    - python: "3.6"
      env: TOXENV=py36
