---
name: "Test"
on:
  pull_request:
  push:
    branches:
      - "qa/**"
      - "stable/**"
jobs:
  test-virtualenv:
    name: "Test (virtualenv)"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v3"
      - name: "Set up Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt
      - name: "Install requirements"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: "Run test"
        run: |
          ./simplebrowsertest.py
  test-docker:
    name: "Test (docker)"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v3"
      - name: "Build containers"
        run: |
          docker build -t archivematica-acceptance-tests --build-arg PYTHON_VERSION .
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          PYTHON_VERSION: "3.9"
      - name: "Run test"
        run: |
          docker run \
            --rm \
            --security-opt="seccomp=unconfined" \
            archivematica-acceptance-tests \
            /home/artefactual/acceptance-tests/simplebrowsertest.py
  lint:
    name: "Lint"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v3"
      - name: "Set up Python"
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt
      - name: "Install tox"
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: "Run tox"
        run: |
          tox -e linting
