---
name: "Test"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "qa/**"
      - "stable/**"
jobs:
  test-virtualenv:
    name: "Test Python ${{ matrix.python-version }} (virtualenv)"
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.8",
          "3.9",
          "3.10",
          "3.11",
          "3.12",
        ]
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: "Install requirements"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: "Run test"
        run: |
          ./simplebrowsertest.py
  test-docker:
    name: "Test Python ${{ matrix.python-version }} (docker)"
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.8",
          "3.9",
          "3.10",
          "3.11",
          "3.12",
        ]
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up buildx"
        uses: "docker/setup-buildx-action@v3"
      - name: "Build the archivematica-acceptance-tests image"
        uses: "docker/build-push-action@v5"
        with:
          target: "archivematica-acceptance-tests"
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}
          tags: "archivematica-acceptance-tests:latest"
          push: false
          load: true
          cache-from: "type=gha,scope=archivematica-acceptance-tests-${{ matrix.python-version }}"
          cache-to: "type=gha,scope=archivematica-acceptance-tests-${{ matrix.python-version }},mode=max"
      - name: "Run test"
        run: |
          docker run \
            --rm \
            --security-opt="seccomp=unconfined" \
            archivematica-acceptance-tests \
            /home/artefactual/acceptance-tests/simplebrowsertest.py
  lint:
    name: "Lint"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt
      - name: "Install tox"
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: "Run tox"
        run: |
          tox -e linting
